import {
  Users01,
  Database01,
  Globe01,
  TrendUp01,
  Star01,
  Mail01,
  Lock01,
  Headphones01,
  CheckCircle,
  Zap,
  Shield01,
  Code01,
  Settings01,
  User01,
  CreditCard01,
} from '@untitledui/icons'

export const PLANS_OPTIONS = [
  {
    id: 'starter',
    name: 'Starter',
    price: '$399',
    period: '/month',
    annualPrice: '$333',
    annualPeriod: '/month',
    annualTotal: '($4,000/year)',
    monthlyTotal: '($4,788/year)',
    members: '10,000',
    collaborators: '3',
    spaces: '100',
    storage: '1TB',
    description: '',
    features: [
      { icon: Users01, text: 'Up to 10,000 members and 3 collaborators' },
      { icon: Database01, text: '100 spaces and 1TB storage' },
      { icon: Globe01, text: 'Custom Domain' },
      { icon: TrendUp01, text: 'Basic Analytics' },
      { icon: Star01, text: 'Core apps: Q&A, Discussion, Events, Polls' },
      { icon: Mail01, text: 'Private messaging & chat' },
      { icon: Lock01, text: 'Social login' },
      { icon: Headphones01, text: 'Chat & Email Support' },
    ],
    buttonText: '14-days trial',
    buttonStyle: 'primary',
  },
  {
    id: 'growth',
    name: 'Growth',
    price: '$1,750',
    period: '/month',
    annualPrice: '$1,500',
    annualPeriod: '/month',
    annualTotal: '($18,000/year)',
    monthlyTotal: '($21,000/year)',
    members: '25,000',
    collaborators: '10',
    spaces: '200',
    storage: '3TB',
    description: '',
    features: [
      { icon: Users01, text: 'Up to 25,000 members and 10 collaborators' },
      { icon: Database01, text: '200 spaces and 3TB storage' },
      { icon: CheckCircle, text: 'Everything in Starter' },
      { icon: Zap, text: 'Ask AI and Federated search' },
      { icon: Shield01, text: "Remove 'Powered by Bettermode'" },
      { icon: Mail01, text: 'Sender email customization' },
      { icon: Code01, text: 'API, Webhooks, and Sandbox Environment' },
      { icon: Settings01, text: 'Activity Log' },
      { icon: Headphones01, text: 'Onboarding and Migration Support' },
      { icon: Lock01, text: 'OAuth2' },
    ],
    buttonText: '14-day trial',
    buttonStyle: 'primary',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Contact Us',
    period: '',
    annualPrice: null,
    annualPeriod: null,
    annualTotal: '',
    monthlyTotal: 'Contact Us',
    members: '50,000',
    collaborators: '20',
    spaces: '500',
    storage: '5TB',
    description: '',
    features: [
      { icon: Users01, text: 'Up to 50,000 members and 20 collaborators' },
      { icon: Database01, text: '500 spaces and 5TB storage' },
      { icon: CheckCircle, text: 'Everything in Growth' },
      { icon: Settings01, text: 'Audit log (90 days)' },
      { icon: Shield01, text: 'SOC II, JWT, and SAML' },
      { icon: User01, text: 'Customer Success Manager' },
      { icon: TrendUp01, text: '99.9% Uptime SLA' },
      { icon: CreditCard01, text: 'Custom billing' },
      { icon: Lock01, text: 'Security and legal review' },
    ],
    buttonText: 'Talk to Sales',
    buttonStyle: 'primary',
  },
]
